query InterviewDashboard(
  $pageNumber: Int!
  $resultsPerPage: Int!
  $sortBy: InterviewDashboardSortBy
  $view: DashboardView
  $sortAscending: Boolean
  $filters: InterviewDashboardFilters
) {
  interviewDashboard(
    pageNumber: $pageNumber
    resultsPerPage: $resultsPerPage
    sortBy: $sortBy
    view: $view
    sortAscending: $sortAscending
    filters: $filters
  ) {
    applicantRecordId
    firstName
    lastName
    position
    applicationStatus
    isApplicantFlagged
    interviewers {
      firstName
      lastName
    }
    interviewScore
  }
}
