query ReviewDashboard(
  $pageNumber: Int!
  $resultsPerPage: Int!
  $sortBy: ReviewDashboardSortBy
  $sortAscending: Boolean
  $filters: ReviewDashboardFilters
  $view: DashboardView
) {
  reviewDashboard(
    pageNumber: $pageNumber
    resultsPerPage: $resultsPerPage
    sortBy: $sortBy
    sortAscending: $sortAscending
    filters: $filters
    view: $view
  ) {
    applicantRecordId
    firstName
    lastName
    position
    timesApplied
    applicationStatus
    choice
    reviewers {
      id
      firstName
      lastName
      email
      position
      role
      isArchived
    }
    totalScore
  }
}
