query ReviewedApplicantRecordsByApplicantRecordId($applicantRecordId: ID!) {
  reviewedApplicantRecordsByApplicantRecordId(
    applicantRecordId: $applicantRecordId
  ) {
    applicantRecord {
      id
      position
      combinedReviewScore
    }
    reviewedApplicantRecords {
      reviewer {
        id
        firstName
        lastName
        email
        role
        position
        isArchived
      }
      reviewedApplicantRecord {
        review {
          passionFSG
          teamPlayer
          desireToLearn
          skill
          skillCategory
          comments
        }
        status
        score
        reviewerHasConflict
      }
    }
  }
}
