import {
  CreateFirebaseFileDTO,
  FirebaseFileDTO,
} from "../../types/firebaseFile";

interface IFirebaseFileService {
  /**
   * Look up a FirebaseFile row by id.
   * @throws if no row exists.
   */
  getFirebaseFileById(id: string): Promise<FirebaseFileDTO>;

  /**
   * Upload a file from the local filesystem to firebase storage, then persist
   * a FirebaseFile row pointing at it. Storage path is generated by the service.
   */
  createFirebaseFile(input: CreateFirebaseFileDTO): Promise<FirebaseFileDTO>;

  /**
   * Delete the firebase storage blob and DB row for the given file. Best-effort:
   * if the storage blob is already gone (or fails to delete) the DB row is still
   * removed. Logged but does not throw on storage failure.
   */
  deleteFirebaseFileById(id: string): Promise<void>;

  /**
   * Generate a short-lived signed URL for the blob at the given storage path.
   */
  getSignedUrl(
    storagePath: string,
    expirationMinutes?: number,
  ): Promise<string>;
}

export default IFirebaseFileService;
