type Query {
  _empty: String
  adminCommentsByApplicantRecordId(applicantRecordId: String!): [AdminCommentDTO!]!
  adminCommentById(id: String!): AdminCommentDTO!
  entity(id: ID!): EntityResponseDTO!
  entities: [EntityResponseDTO!]!
  entitiesCSV: String!
  file(fileUUID: ID!): String!
  getInterviewDelegation(interviewedApplicantRecordId: ID!, interviewerId: Int!): InterviewDelegation!
  getInterviewGroupById(id: ID!): InterviewGroupDTO!
  getInterviewedApplicantsByUserId(userId: Int!): [InterviewedApplicantsDTO!]!
  getInterviewedPairingsByUserId(userId: Int!): [InterviewPairingsDTO!]!
  getInterviewersByGroupId(groupId: ID!): [UserDTO!]!
  getInterviewedApplicantRecordById(id: ID!): InterviewedApplicantRecord!
  reviewDashboard(pageNumber: Int!, resultsPerPage: Int!): [ReviewDashboardRowDTO!]!
  reviewDashboardSidePanel(applicantId: String!): ReviewDashboardSidePanelDTO!
  getReviewedApplicantRecord(applicantRecordId: ID!, reviewerId: Int!): ReviewedApplicantRecord!
  reviewApplicantPage(applicantRecordId: String!): ApplicationDTO!
  getReviewedApplicantsByUserId(userId: Int!): [ReviewedApplicantsDTO!]!
  simpleEntity(id: ID!): SimpleEntityResponseDTO!
  simpleEntities: [SimpleEntityResponseDTO!]!
  simpleEntitiesCSV: String!
  userById(id: ID!): UserDTO!
  userByEmail(email: String!): UserDTO!
  users: [UserDTO!]!
  usersCSV: String!
}

type Mutation {
  _empty: String
  createAdminComment(adminComment: CreateAdminCommentDTO!): AdminCommentDTO!
  updateAdminComment(id: String!, content: CreateAdminCommentDTO!): AdminCommentDTO!
  deleteAdminCommentById(id: String!): AdminCommentDTO!
  updateApplicantStatus(applicantRecordId: String!, status: ApplicationStatus!): ApplicantRecordDTO!
  bulkUpdateApplicantStatus(applicantRecordIds: [String!]!, status: ApplicationStatus!): [ApplicantRecordDTO!]!
  setApplicantRecordFlag(applicantRecordId: String!, flagValue: Boolean!): ApplicantRecordDTO!
  login(email: String!, password: String!): AuthDTO!
  loginWithGoogle(idToken: String!): AuthDTO!
  register(user: RegisterUserDTO!): AuthDTO!
  refresh: String!
  logout(userId: ID!): ID
  resetPassword(email: String!): Boolean!
  createEntity(entity: EntityRequestDTO!, file: Upload): EntityResponseDTO!
  updateEntity(id: ID!, entity: EntityRequestDTO!, file: Upload): EntityResponseDTO!
  deleteEntity(id: ID!): ID
  delegateInterviewers(positions: [String!]!): [InterviewDelegation!]!
  createInterviewDelegation(interviewedApplicantRecordId: ID!, interviewerId: Int!, groupId: ID!): InterviewDelegation!
  updateInterviewDelegation(interviewedApplicantRecordId: ID!, prevInterviewerId: Int!, newInterviewerId: Int!, groupId: ID!): InterviewDelegation!
  deleteInterviewDelegation(interviewedApplicantRecordId: ID!, interviewerId: Int!): InterviewDelegation!
  bulkCreateInterviewDelegations(delegations: [BulkCreateInterviewDelegationInput!]!): [InterviewDelegation!]!
  bulkDeleteInterviewDelegations(delegations: [BulkDeleteInterviewDelegationInput!]!): [InterviewDelegation!]!
  createInterviewGroup(interviewGroup: CreateInterviewGroupDTO!): InterviewGroupDTO!
  updateInterviewGroup(id: ID!, interviewGroup: UpdateInterviewGroupDTO!): InterviewGroupDTO!
  deleteInterviewGroupById(id: ID!): InterviewGroupDTO!
  bulkCreateInterviewGroups(interviewGroups: [CreateInterviewGroupDTO]!): [InterviewGroupDTO]!
  bulkDeleteInterviewGroupsByIds(interviewGroupIds: [ID]!): [InterviewGroupDTO]!
  createInterviewedApplicantRecord(applicantRecordId: String!, score: Int, interviewJSON: InterviewInput, status: InterviewStatus, interviewNotesId: String, interviewDate: String): InterviewedApplicantRecord!
  updateInterviewedApplicantRecord(id: ID!, score: Int, interviewJSON: InterviewInput, status: InterviewStatus, interviewNotesId: String, interviewDate: String): InterviewedApplicantRecord!
  deleteInterviewedApplicantRecordById(id: ID!): InterviewedApplicantRecord!
  delegateReviewers(positions: [String!]!): [ReviewedApplicantRecordDTO!]!
  createReviewedApplicantRecord(input: CreateReviewedApplicantRecordInput!): ReviewedApplicantRecord!
  bulkCreateReviewedApplicantRecord(inputs: [CreateReviewedApplicantRecordInput!]!): [ReviewedApplicantRecord!]!
  deleteReviewedApplicantRecord(input: DeleteReviewedApplicantRecord!): ReviewedApplicantRecord!
  bulkDeleteReviewedApplicantRecord(inputs: [DeleteReviewedApplicantRecord!]!): [ReviewedApplicantRecord!]!
  updateReviewedApplicantRecord(input: UpdateReviewedApplicantRecordInput!): ReviewedApplicantRecord!
  reportReviewConflict(applicantRecordId: String!, reviewerId: Int!): ReviewedApplicantRecordDTO!
  createSimpleEntity(entity: SimpleEntityRequestDTO!): SimpleEntityResponseDTO!
  updateSimpleEntity(id: ID!, entity: SimpleEntityRequestDTO!): SimpleEntityResponseDTO!
  deleteSimpleEntity(id: ID!): ID
  createUser(user: CreateUserDTO!): UserDTO!
  updateUser(id: ID!, user: UpdateUserDTO!): UserDTO!
  deleteUserById(id: ID!): ID
  deleteUserByEmail(email: String!): ID
}

type AdminCommentDTO {
  id: String!
  userId: Int!
  applicantRecordId: String!
  comment: String!
  createdAt: String!
  updatedAt: String!
}

input CreateAdminCommentDTO {
  userId: Int!
  applicantRecordId: String!
  comment: String!
}

enum ApplicationStatus {
  Applied
  InReview
  Reviewed
  Selected
  Interviewed
  Offer
  Rejected
}

type ApplicantRecordDTO {
  id: String!
  applicantId: String!
  position: String!
  roleSpecificQuestions: [String!]!
  choice: Int!
  status: ApplicationStatus!
  skillCategory: String
  combined_score: Int
  isApplicantFlagged: Boolean!
}

type AuthDTO {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  role: Role!
  position: String
  isArchived: Boolean!
  accessToken: String!
}

input RegisterUserDTO {
  firstName: String!
  lastName: String!
  email: String!
  password: String!
}

enum Enum {
  A
  B
  C
  D
}

scalar Upload

type EntityResponseDTO {
  id: ID!
  stringField: String!
  intField: Int!
  enumField: Enum!
  stringArrayField: [String]!
  boolField: Boolean!
  fileName: String
}

input EntityRequestDTO {
  stringField: String!
  intField: Int!
  enumField: Enum!
  stringArrayField: [String]!
  boolField: Boolean!
  filePath: String
  contentType: String
}

enum InterviewConflict {
  APPLICANT_CONFLICT
  APPLICANT_NO_RESPONSE
  PARTNER_NO_RESPONSE
  CANNOT_ATTEND
}

type InterviewDelegation {
  interviewedApplicantRecordId: ID!
  interviewerId: Int!
  interviewHasConflict: InterviewConflict
  groupId: ID!
}

input BulkCreateInterviewDelegationInput {
  interviewedApplicantRecordId: ID!
  interviewerId: Int!
  groupId: ID!
}

input BulkDeleteInterviewDelegationInput {
  interviewedApplicantRecordId: ID!
  interviewerId: Int!
}

type InterviewGroupDTO {
  id: ID!
  schedulingLink: String
  status: String!
}

input CreateInterviewGroupDTO {
  schedulingLink: String
  status: String!
}

input UpdateInterviewGroupDTO {
  schedulingLink: String
  status: String!
}

type InterviewedApplicantsDTO {
  applicantRecordId: String!
  interviewStatus: String!
  applicantFirstName: String!
  applicantLastName: String!
}

type InterviewPairingsDTO {
  interviewedGroupId: ID!
  interviewGroupStatus: String!
  groupMembers: [UserDTO!]!
}

enum InterviewStatus {
  NeedsReview
  InProgress
  Complete
}

type Interview {
  passionFSG: Int
  teamPlayer: Int
  desireToLearn: Int
  skill: Int
  skillCategory: SkillCategory
  comments: String
}

input InterviewInput {
  passionFSG: Int
  teamPlayer: Int
  desireToLearn: Int
  skill: Int
  skillCategory: SkillCategory
  comments: String
}

type InterviewedApplicantRecord {
  id: ID!
  applicantRecordId: String!
  score: Int
  interviewJson: Interview
  status: InterviewStatus!
  interviewNotesId: String
  interviewDate: String
}

type ReviewerDTO {
  firstName: String!
  lastName: String!
}

type ReviewDashboardRowDTO {
  firstName: String!
  lastName: String!
  position: String!
  timesApplied: String!
  applicationStatus: String!
  choice: Int!
  reviewers: [ReviewerDTO!]!
  totalScore: Int
}

type ReviewDetails {
  reviewerFirstName: String!
  reviewerLastName: String!
  review: Review!
}

type ReviewDashboardSidePanelDTO {
  firstName: String!
  lastName: String!
  positionTitle: String!
  program: String!
  resumeUrl: String!
  applicationStatus: String!
  skillCategory: String
  reviewDetails: [ReviewDetails!]!
}

enum SkillCategory {
  JUNIOR
  INTERMEDIATE
  SENIOR
}

type Review {
  passionFSG: Int
  teamPlayer: Int
  desireToLearn: Int
  skill: Int
  skillCategory: SkillCategory
  comments: String
}

input ReviewInput {
  passionFSG: Int
  teamPlayer: Int
  desireToLearn: Int
  skill: Int
  skillCategory: SkillCategory
}

type ReviewedApplicantRecord {
  applicantRecordId: ID!
  reviewerId: Int!
  review: Review
  status: String
  score: Int
  reviewerHasConflict: Boolean
}

input CreateReviewedApplicantRecordInput {
  applicantRecordId: ID!
  reviewerId: Int!
  review: ReviewInput
  status: String
}

input DeleteReviewedApplicantRecord {
  applicantRecordId: ID!
  reviewerId: Int!
}

input UpdateReviewedApplicantRecordInput {
  applicantRecordId: ID!
  reviewerId: Int!
  review: ReviewInput
  status: String
}

type ShortQuestionAnswer {
  question: String!
  response: String!
}

type ApplicationDTO {
  id: String!
  academicOrCoop: String!
  academicYear: String!
  email: String!
  firstChoiceRole: String!
  firstName: String!
  heardFrom: String!
  lastName: String!
  locationPreference: String!
  program: String!
  pronouns: String!
  pronounsSpecified: String!
  resumeUrl: String!
  roleSpecificQuestions: [String!]!
  secondChoiceRole: String!
  shortQuestionAnswers: [ShortQuestionAnswer!]!
  status: String!
  secondChoiceStatus: String!
  term: String!
  timesApplied: String!
  timestamp: Int
}

type ReviewedApplicantsDTO {
  applicantRecordId: String!
  reviewStatus: String!
  applicantFirstName: String!
  applicantLastName: String!
}

type ReviewedApplicantRecordDTO {
  applicantRecordId: String!
  reviewerId: Int!
  review: Review!
  status: String!
  score: Int
  reviewerHasConflict: Boolean!
}

enum SimpleEntityEnum {
  A
  B
  C
  D
}

type SimpleEntityResponseDTO {
  id: ID!
  stringField: String!
  intField: Int!
  enumField: SimpleEntityEnum!
  stringArrayField: [String]!
  boolField: Boolean!
}

input SimpleEntityRequestDTO {
  stringField: String!
  intField: Int!
  enumField: Enum!
  stringArrayField: [String]!
  boolField: Boolean!
}

enum Role {
  User
  Admin
  SuperAdmin
}

type UserDTO {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  role: Role!
  position: String
  isArchived: Boolean!
}

input CreateUserDTO {
  firstName: String!
  lastName: String!
  email: String!
  role: Role!
  password: String!
  position: String
  isArchived: Boolean!
}

input UpdateUserDTO {
  firstName: String!
  lastName: String!
  email: String!
  role: Role!
  position: String
  isArchived: Boolean!
}
